### ISSUE TITLE
PT not launching

### ISSUE THREAD

**Issue by brianx87** [Matoking/protontricks#246]
Receiving the following error when launching PT. I've removed the list of non-steam game shortcuts from the error message as the list was quite long. Tried reinstalling and restarting with no luck.

```
Protontricks was closed due to the following error:



Traceback (most recent call last):

  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save

    rawmode = RAWMODE[im.mode]

KeyError: 'P'



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper

    return cli_func(self, *args, **kwargs)

  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main

    steam_app = select_steam_app_with_gui(

  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui

    appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)

  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon

    resized_img.save(icon_cache_path)

  File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save

    save_handler(self, fp, filename)

  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save

    raise OSError(msg) from e

OSError: cannot write mode P as JPEG





=============



Please include this entire error message when making a bug report.

Log messages:



Running inside Flatpak sandbox, version 1.12.4.

Found Steam directory at /home/deck/.local/share/Steam

Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime

WINETRICKS environment variable is not available. Searching from $PATH.

Found 2 Steam library folders

Multiple compatdata directories found for app 275850

Multiple compatdata directories found for app 304240

Multiple compatdata directories found for app 2310

Multiple compatdata directories found for app 377160

Currently logged-in Steam user: 

Shortcut Konsole (4155333422) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.

Found 7 Steam shortcuts running using Steam compatibility tools

Using 'yad' as GUI provider

App icon /home/deck/.local/share/Steam/appcache/librarycache/1092660_icon.jpg has unusual size, resizing
```

**Comment by kristoffertell** [comment]
I'm having the exact same issue on Steam Deck since updating to protontricks 1.10.4.

**Comment by shinseitom** [comment]
Similar issue here, except instead of "P as JPEG" it's "RGBA as JPEG"
In my case, seems to be related to using custom icons from SteamGridDB.  Downgrading using the command from @kristoffertell  got the gui to open.

**Comment by Jlom93** [comment]
> I'm having the same issue.
> 
> > `Protontricks was closed due to the following error:
> > Traceback (most recent call last):
> > File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
> > rawmode = RAWMODE[im.mode]
> > KeyError: 'P'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
> > return cli_func(self, *args, **kwargs)
> > File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main
> > steam_app = select_steam_app_with_gui(
> > File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui
> > appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
> > File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon
> > resized_img.save(icon_cache_path)
> > File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save
> > save_handler(self, fp, filename)
> > File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
> > raise OSError(msg) from e
> > OSError: cannot write mode P as JPEG
> 
> @kristoffertell, unfortunately your suggestion didn't work but thank you!

I have fixed the issue. 

The last line of the log report says 

> App icon /home/deck/.local/share/Steam/appcache/librarycache/1092660_icon.jpg has unusual size, resizing

Your specific icon will be different but you need to locate the icon mentioned above, in the same directory. Once done so, open the image and it will show you its dimension - this needs to be 32x32 however most icons are 512x512. 

If you have a photo editor like GIMP installed then you can resize the image to 32x32. if not, you can visit sites like iloveimg.com which will resize the image to your specific dimensions. 

Replace the old icon with the new one, keep the names exactly the same. 

Once you've replaced this icon PT should open without any problems. 

If multiple icon are highlighted you will need to replace all of them.

**Comment by Matoking** [comment]
I pushed a small fix to icon conversion that should _hopefully_ fix this. You can install the development version with this fixed applied using the following command:

```
flatpak install --user https://dl.flathub.org/build-repo/44386/com.github.Matoking.protontricks.flatpakref
```

Does this fix the bug?

**Comment by JooZehh** [comment]
It has!!! Thank you very much for the update

**Comment by itsFurty** [comment]
> I pushed a small fix to icon conversion that should _hopefully_ fix this. You can install the development version with this fixed applied using the following command:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/44386/com.github.Matoking.protontricks.flatpakref
> ```
> 
> Does this fix the bug?

Im still experiencing an error that is probably unrelated to the icon resizing.

> Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main
    steam_app = select_steam_app_with_gui(
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui
    appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon
    resized_img.save(icon_cache_path)
  File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Steam library folder /run/media/deck/095586ce-8854-484e-bf21-5dd72da9d84e not found. Protontricks might not have access to the directory.
Currently logged-in Steam user: madyakker
Shortcut EmulationStation-DE-x64_SteamDeck.AppImage (3565998972) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Lutris (3069490068) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut ZDL (2261680366) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Gears of War 3 (3310644220) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Halo 4 (2942958782) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Castlevania The Lecarde Chronicles 2 up.exe (2847072901) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metroid Prime (3140594531) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metroid Prime 2: Echoes (2903270647) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metroid Prime 3: Corruption (2205486212) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Mario 64 R96 (2750230260) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Breath of the Wild (3807910119) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Killzone (2236947260) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ratchet & Clank Future: Quest for Booty (2535687649) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Singularity.ps3 (2542399692) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut EmulationStation (3287732162) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut yuzu (3766390893) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut xemu (emulator) (2957850091) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Vita3K (2905070726) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut RPCS3 (3135345479) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut RetroArch (3818674851) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut PrimeHack (3051925362) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut PPSSPP (2479737991) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut pcsx2-qt (3957404336) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut DuckStation (Emulator) (2498926476) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Dolphin (4149670527) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Cemu (3538053848) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Spec Ops The Line.ps3 (4216668638) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Call of Duty: Modern Warfare 3 (3147856237) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Everybody's Golf 6 (Hot Shots Golf: World Invitational) (2457512434) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Medal of Honor: Frontline (2590311137) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut God of War HD (3666209392) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut God of War: Chains of Olympus HD (2996380331) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut God of War: Ghost of Sparta HD (3533391217) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut God of War II HD (3812310288) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Call of Duty: Black Ops 2 (4195108589) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Resistance 2.ps3 (3803554159) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Resistance: Fall of Man (2212911955) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Resident Evil Revelations (4115233410) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Tears of the Kingdom (2499974701) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Mario Odyssey (2878064469) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metroid Prime Remastered (3546058246) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario + Rabbids Sparks of Hope (3930177910) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Luigi's Mansion 3 (2317264119) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Advance Wars 1 plus 2 Re-Boot Camp [0100300012F2A000][v0][US](nsw2u.com) (2729786537) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Xenia (3019226337) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut FINAL FANTASY II (3972107156) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut FINAL FANTASY III (3729832853) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut FINAL FANTASY IV (2448208664) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut FINAL FANTASY V (2468643491) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut FINAL FANTASY VI (3287225399) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Starsector (2524347666) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut DukeForever.exe (3214749563) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Marathon (4137974543) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Marathon 2: Durandal (2937835079) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Marathon Infinity (2193995430) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Wildermyth (3219474972) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Warhammer 40,000 Boltgun (3295986937) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Simpsons: Hit and Run (2427625006) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Smash Bros. Ultimate (3697407919) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Metal Gear Solid 4: Guns of the Patriots (3548679205) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut NBA Jam Legends on Fire (2215959251) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut NPUB30585 (3456158159) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Resistance: Fall of Man (3942569438) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Astral Chain (2582115721) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Mega Baseball 4 (3094572637) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Legend Bowl (2599460393) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut We Love Katamari REROLL+ Royal Reverie (3464486984) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut OpenMW Launcher (3876125752) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Ocarina of Time (4091202118) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Majora's Mask (2337563161) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut NPUB01043 (3757408367) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Family Guy: Back to the Multiverse (2767393095) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Gears of War 3 (2526315963) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Gears of War 2 (4244666721) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Tetris Effect: Connected (2960206470) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Family Guy: Back to the Multiverse (3804292519) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Wipeout HD (3553470762) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut SeaOfStars.exe (2910963599) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 27 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/appcache/librarycache/1086940_icon.jpg has unusual size, resizing

**Comment by kristoffertell** [comment]
> I pushed a small fix to icon conversion that should _hopefully_ fix this. You can install the development version with this fixed applied using the following command:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/44386/com.github.Matoking.protontricks.flatpakref
> ```
> 
> Does this fix the bug?

Not for me, unfortunately:

`Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main
    steam_app = select_steam_app_with_gui(
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui
    appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
  File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon
    resized_img.save(icon_cache_path)
  File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG`

**Comment by Matoking** [comment]
> > I pushed a small fix to icon conversion that should _hopefully_ fix this. You can install the development version with this fixed applied using the following command:
> > ```
> > flatpak install --user https://dl.flathub.org/build-repo/44386/com.github.Matoking.protontricks.flatpakref
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does this fix the bug?
> 
> Not for me, unfortunately:
> 
> > Protontricks was closed due to the following error:
> > Traceback (most recent call last):
> > File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 639, in _save
> > rawmode = RAWMODE[im.mode]
> > KeyError: 'RGBA'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "/app/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
> > return cli_func(self, *args, **kwargs)
> > File "/app/lib/python3.10/site-packages/protontricks/cli/main.py", line 264, in main
> > steam_app = select_steam_app_with_gui(
> > File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 318, in select_steam_app_with_gui
> > appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
> > File "/app/lib/python3.10/site-packages/protontricks/gui.py", line 104, in _get_appid2icon
> > resized_img.save(icon_cache_path)
> > File "/app/lib/python3.10/site-packages/PIL/Image.py", line 2413, in save
> > save_handler(self, fp, filename)
> > File "/app/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
> > raise OSError(msg) from e
> > OSError: cannot write mode RGBA as JPEG

The image mode should have been converted to `RGB` at that point, but the exception seems to show that image with `RGBA` (i.e. with an alpha channel) being written.

Please check if the correct version is installed by running these commands:

```
$ flatpak run --command=bash com.github.Matoking.protontricks
# Run the following inside the new shell
$ grep 'resized_img' /app/lib/python3.10/site-packages/protontricks/gui.py
                    resized_img = img.resize(APP_ICON_SIZE).convert("RGB")
                    resized_img.save(icon_cache_path)
```

The `grep` command should print a line with `convert("RGB")`, indicating the development version is installed. If not, something else is going on.

**Comment by kristoffertell** [comment]
> The image mode should have been converted to `RGB` at that point, but the exception seems to show that image with `RGBA` (i.e. with an alpha channel) being written.
> 
> Please check if the correct version is installed by running these commands:

You were right, I was indeed running the wrong version.

Managed to actually install and run the dev version and it seems to run perfectly now :)

**Comment by brianx87** [comment]
> ```
> flatpak install --user https://dl.flathub.org/build-repo/44386/com.github.Matoking.protontricks.flatpakref
> ```

No, not for me it doesn't.

**Comment by willnix86** [comment]
I'm still seeing this issue on my Steam Deck. Tried the above but the link says "server not found"

**Comment by Matoking** [comment]
I released 1.10.5 with the icon conversion fix, which should fix this problem.

**Comment by willnix86** [comment]
I'll see what version I have. It certainly appears to be the latest one available on the Discover app, but I'll confirm
