### ISSUE TITLE
Protontricks GUI fails to run.

### ISSUE THREAD

**Issue by delicio** [Matoking/protontricks#439]
**Describe the bug**

When trying to run Protontricks GUI, it fails showing the error `/usr/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" `

**To Reproduce**

1. Run command `protontricks --gui`;
2. Choose any game;
3. Click OK on error `Unknown file arch of /home/user/.cache/protontricks/proton/Proton Experimental/bin/wineserver.` ;
4. Click OK on error `You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.`;
5. Click OK on error `WoW64 type could not be detected.`;
6. Click OK on info 

```
WINEPREFIX INFO:
Drive C: total 36
drwxr-xr-x  9 user user 4096 ago 17 20:14 .
drwxr-xr-x  4 user user 4096 set 21 00:51 ..
drwxr-xr-x  2 user user  4096 set 20 00:44 openxr
drwxr-xr-x  4 user user  4096 ago 17 20:14 ProgramData
drwxr-xr-x  6 user user  4096 ago 17 20:14 Program Files
drwxr-xr-x  7 user user 4096 ago 17 20:14 Program Files (x86)
drwxr-xr-x  5 user user 4096 set 21 00:51 users
drwxr-xr-x  3 user user  4096 ago 17 20:14 vrclient
drwxr-xr-x 22 user user  4096 set 20 00:44 windows

Registry info:
/mnt/2009f54c-1a4a-4b8c-ad8d-df0a2084636b/SteamLibrary/steamapps/compatdata/379430/pfx/system.reg:#arch=win64
/mnt/2009f54c-1a4a-4b8c-ad8d-df0a2084636b/SteamLibrary/steamapps/compatdata/379430/pfx/userdef.reg:#arch=win64
/mnt/2009f54c-1a4a-4b8c-ad8d-df0a2084636b/SteamLibrary/steamapps/compatdata/379430/pfx/user.reg:#arch=win64
```
7. Click OK on error `/usr/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" `;
8. GUI closes.

**Expected behavior**

After step 6, the GUI should open and show protontricks options.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks installation method: AUR
 - Protontricks version: 1.13.0
 - Steam version:
```
Steam Beta Branch:  Steam Beta Update
Steam Version:  1758328855
Steam Client Build Date:  Fri, Sep 19 9:17 PM UTC -08:00
Steam Web Build Date:  Fri, Sep 19 9:14 PM UTC -08:00
Steam API Version:  SteamClient023

```

**Comment by Matoking** [comment]
Could you try running Protontricks from the command-line with the `-vv` flag and copy the output to [gist.github.com][https://gist.github.com]? For example:

```sh
$ protontricks -vv --gui
```

I suspect something with Steam Linux Runtime might be failing for some reason, but the error messages for that are not captured for the error dialog. Last time this was caused by having a directory in the root filesystem with symbols that Steam Runtime cannot handle (eg. `/directory:name`). If Protontricks works with `--no-bwrap` flag, then that would probably explain it.

**Comment by delicio** [comment]
> Could you try running Protontricks from the command-line with the `-vv` flag and copy the output to [gist.github.com][https://gist.github.com]?

https://gist.github.com/delicio/7d17827ed03b99ea76781e5a3469953c

> If Protontricks works with `--no-bwrap` flag, then that would probably explain it.

Tried with `--no-bwrap` and the issue persists.

**Comment by Matoking** [comment]
OK, I was hoping for the additional logs to provide additional clues. But nothing seems to stand out except for the Wine executables failing to run, explaining the empty results; bwrap launcher failing to start usually explains that, but it seems to start correctly, and as you stated, the issue persists even with it disabled.

We could instead try running Wine commands directly - skipping Winetricks - and see if anything comes up that way.

```sh
$ protontricks --command "bash -x wine --version" 379430
```

This will produce verbose output, which should be posted to [gist.github.com](https://gist.github.com). Thanks for the logs so far!

**Comment by delicio** [comment]
> Thanks for the logs so far!

Sure, thanks for the help!

> We could instead try running Wine commands directly - skipping Winetricks - and see if anything comes up that way.

Here is the log: https://gist.github.com/delicio/ad9f5ebc562b1fc8556098c761c023f8

**Comment by Matoking** [comment]
Well, that's not what I was expecting. `warning: /usr/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" ` error message in your previous log indicated that a problem with running Wine commands could've been the problem. But that's not the case here, the version is printed correctly and the setup looks correct.

We could try running that command directly to see if anything comes up.

```sh
protontricks --command "wine cmd.exe /c echo '%AppData%'" 379430
```

In my case, the last line is `C:\users\steamuser\AppData\Roaming`, which is the configuration value that Winetricks is trying to retrieve. Does that line appear and what are the preceding lines?

Also, does this issue occur with any other games? What if you try enabling GE-Proton 10-15 for a newly installed game, launching the game and then try launching it via Protontricks?

**Comment by delicio** [comment]
> In my case, the last line is `C:\users\steamuser\AppData\Roaming`, which is the configuration value that Winetricks is trying to retrieve. Does that line appear and what are the preceding lines?

The same line appears to me, but apparently there are errors before. Take a look: https://gist.github.com/delicio/d2448ade1d10293fc9da41e781d0ba62

> Also, does this issue occur with any other games? What if you try enabling GE-Proton 10-15 for a newly installed game, launching the game and then try launching it via Protontricks?

It occurs with any game, even after deleting the Steam library folder, the folders and configuration files of Steam, wine, winetricks, protontricks etc. 

It also happens with any version of Proton.

I tried launching the game as you instructed, but the error persists.

**Comment by Matoking** [comment]
The warnings preceding the line seem benign and unrelated (`fixme` messages are very common). The important thing is that the correct configuration value is being printed here, but not when running Winetricks for whatever reason. My guess would be that your Winetricks installation is changing the Wine environment variables (probably to the Wine executables?) and breaking in the process, though I don't recall it ever doing that before.

You could try running the following and posting the output:

```sh
$ protontricks --command "bash -x winetricks good" 379430
```

The command performs the Winetricks startup procedures and prints the message "good succeeded!" if everything went correctly. But it will likely fail before that as it did before.

**Comment by delicio** [comment]
Here's the output:

https://gist.github.com/delicio/410a7fb45acaa69afd661bbdbcf25940

**Comment by Matoking** [comment]
Agh, the error message has been staring at my face all this time with the `/usr/bin/wine`  path. 🤦 

You have set `WINE` before launching Protontricks somewhere, likely in `~/.bashrc`, `~/.profile` or some other place. Run `bash -v` and it will print a list of all the files it reads before starting the shell proper. Check for `export WINE=...` or similar lines; the preceding comment should tell where the file is.

Protontricks honors the existing value, though in this case it causes a problem since it doesn't match what `WINESERVER` will be set to, explaining the crashes. It would probably be ideal to print a warning in case one or the other is set, but not both.

**Comment by delicio** [comment]
> or some other place

I guess it is, then. 😂

I can't see the error in the `bash -v` output. Unfortunately, I'm just a regular user. What can you conclude from this output?

https://gist.github.com/delicio/e665dff20b50de7d5d43339c6bbbbe60

**Comment by Matoking** [comment]
> > or some other place
> 
> I guess it is, then. 😂
> 
> I can't see the error in the `bash -v` output. Unfortunately, I'm just a regular user. What can you conclude from this output?
> 
> https://gist.github.com/delicio/e665dff20b50de7d5d43339c6bbbbe60

Sorry for the late reply.

There's a `export WINE=/usr/bin/wine` line in your `~/.bashrc` file. Removing that line and restarting the terminal should fix it.

**Comment by delicio** [comment]
What's confusing me is that I had to unset the environment variables for Wine and Winetricks. Simply deleting them from bashrc didn't solve the problem.

But now it's up to me to learn what I did wrong. :)

I hope this thread can be useful to other people having the same issue.

Thanks a lot for the help.
