### ISSUE TITLE
Stop suggesting running pip as root

### ISSUE THREAD

**Issue by altendky** [Matoking/protontricks#9]
Mostly the system pip shouldn't be run at all, but especially not with root.  There is a warning about it possibly causing issues but it would be better to actively discourage it and show the reasonable alternatives.

Here's a reference PR.
https://github.com/pypa/virtualenv/pull/1283/files

There's pipx, pipsi, and venvs for managing envs for installing packages as 'programs', as opposed to for development.  There's both virtualenv and venv for manually creating the virtual environment.

Keep in mind that `--user` can still cause trouble with system packages.  It's less hazardous than using `sudo` with pip or otherwise running it as root, but it can still break the system packages for the user that does the install.

[bit.ly/py-env](bit.ly/py-env) is an intro to setting up envs.

**Comment by Matoking** [comment]
I've updated the README with instructions on using pipx instead of pip. There's still a few cases where someone may prefer pip despite the possible problems (eg. Python version is 3.4 or 3.5), so I've kept it with the disclaimer that it's not recommended.

The ideal solution would be to have packages for the most common distributions, but that isn't very easy to solve.

**Comment by altendky** [comment]
Thanks for the change and for doing it so quickly.  :]  In general I figure that if someone is in a position that they can make an informed decision about using sudo with pip they will know how to use pip.  I rarely find people that understand what happens when pip'ing into the system, even if they have extensive knowledge about pip etc.

Cheers.

**Comment by RussianNeuroMancer** [comment]
> I've kept it with the disclaimer that it's not recommended

Thank you. pipx installation didn't work for me. After step "Close and reopen your terminal." pipx is still not found, unless I did "sudo apt install pipx", and then after successfull protontricks installation, protontricks command still not working. 

Installing with "sudo apt install python3-pip python3-setuptools" and "sudo python3 -m pip install protontricks" solved this, and now protontricks works.

**Comment by altendky** [comment]
@RussianNeuroMancer what about it didn't work?  And no, using sudo isn't the solution.  Mostly just a good way to make a mess (that hopefully hasn't broken anything else).  Also, this sounds like a separate ticket.

**Comment by RussianNeuroMancer** [comment]
@altendky as I said

> After step "Close and reopen your terminal." pipx is still not found

Just regular command not found error.

> And no, using sudo isn't the solution. Mostly just a good way to make a mess (that hopefully hasn't broken anything else). 

I understand your will to make world a better place with less issues on end user side. But, honestly, deb package build script or PPA would help 1000x more than two other ways of installing protontricks (one that doesn't work and another that could break installed software).

> Also, this sounds like a separate ticket.

Yeah, one that probably should go to https://github.com/pipxproject/pipx/issues as it's seems like "~/.local/bin/pipx ensurepath" didn't work out as expected.

But, hey, I just helped friend's kid with installing faudio for Skyrim: SE, find that one of two installation methods not working, and let developer know about it. That it. It's not like I have to travel into world of Python package managers that I didn't want to deal with in first place (and you most likely know why I feel this way).
